### PR TITLE
le pull request

### PR DESCRIPTION
**Pull request by astral-carrier**
pull request to get my changes to haze's repo. Use at will.

### CODE REVIEW

**Comment by awesomehaze** [comment]
It can already verify emails not in emailDict

**Comment by awesomehaze** [comment]
Please explain

**Comment by astral-carrier** [comment]
image

This is the part that checks users not in the emailDict. 

3 reasons why it no work: 

1. student email addresses end in @mylcusd.net, not @lcusd.net, but they should still be verified
2. student email addresses have a number at the end, but you don't account for that. 
3. some people's accounts have a middle name, in which case `name.split(' ')[1]` would return the middle name, not the last name.

**Comment by awesomehaze** [comment]
I agree with the third point, is name.split(' ')[-1] more to your liking?
This tool is more for verifying staff members, not many people will try to imitate students to try to get information from people.

**Comment by astral-carrier** [comment]
javascript doesn't allow negative indices lol. 

I already made it get the last part of the name. There is still one minor problem with that but i'll elaborate later

**Pull request closed without merging**
